<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE config [
<!ELEMENT config (gpios*, switchs*, calendars*, scheduledswitchs*)>

<!ELEMENT gpios (gpio+)>

<!ELEMENT gpio (#PCDATA)>
<!ATTLIST gpio name CDATA #REQUIRED>
<!ATTLIST gpio id CDATA #REQUIRED>
<!ATTLIST gpio type CDATA #REQUIRED>

<!ELEMENT switchs (switch*, inverseswitch*)>

<!ELEMENT switch (#PCDATA)>
<!ATTLIST switch name CDATA #REQUIRED>
<!ATTLIST switch gpioname CDATA #REQUIRED>

<!ELEMENT inverseswitch (#PCDATA)>
<!ATTLIST inverseswitch name CDATA #REQUIRED>
<!ATTLIST inverseswitch gpioname CDATA #REQUIRED>

<!ELEMENT calendars (hourlycalendar*, dailycalendar*, weeklycalendar*, monthlycalendar*, combinedcalendar*)>

<!ELEMENT hourlycalendar (#PCDATA)>
<!ATTLIST hourlycalendar name CDATA #REQUIRED>
<!ATTLIST hourlycalendar hours CDATA #REQUIRED>

<!ELEMENT dailycalendar (#PCDATA)>
<!ATTLIST dailycalendar name CDATA #REQUIRED>
<!ATTLIST dailycalendar days CDATA #REQUIRED>

<!ELEMENT weeklycalendar (#PCDATA)>
<!ATTLIST weeklycalendar name CDATA #REQUIRED>
<!ATTLIST weeklycalendar weekdays CDATA #REQUIRED>

<!ELEMENT monthlycalendar (#PCDATA)>
<!ATTLIST monthlycalendar name CDATA #REQUIRED>
<!ATTLIST monthlycalendar weekdays CDATA #REQUIRED>

<!ELEMENT combinedcalendar (#PCDATA)>
<!ATTLIST combinedcalendar name CDATA #REQUIRED>
<!ATTLIST combinedcalendar liste CDATA #REQUIRED>

<!ELEMENT scheduledswitchs (scheduledswitch*)>

<!ELEMENT scheduledswitch  (#PCDATA)>
<!ATTLIST scheduledswitch name CDATA #REQUIRED>
<!ATTLIST scheduledswitch switch CDATA #REQUIRED>
<!ATTLIST scheduledswitch calendar CDATA #REQUIRED>

]>

<config>

<gpios>
	<gpio name="pompegpio" id="6" type="output" />
	<gpio name="robotgpio" id="8" type="output" />
	<gpio name="lumieregpio" id="8" type="output" />
	
</gpios>

<switchs>
	<switch name="pompeswitch" gpioname="pompegpio"/>
	<inverseswitch name="robotswitch" gpioname="robotgpio"/>
	<inverseswitch name="lumiereswitch" gpioname="lumieregpio"/>
</switchs>

<calendars>
<hourlycalendar name="pompecal" hours="7,8,9,10,11,12,13,14,15,16,17,18"/>
<hourlycalendar name="robotcal" hours="8,9"/>
<hourlycalendar name="lumierecal" hours="22,23,0"/>
<dailycalendar name="JoursPairs" days="2,4,6,8,10,12,14,16,18,20,22,24,26,28,30"/>
<weeklycalendar name="WeekEndDays" weekdays="6,7"/>
<weeklycalendar name="WeekDays" weekdays="1,2,3,4,5"/>
<combinedcalendar name="CalLumiereWeekEnd" liste="lumierecal,WeekEndDays" />
</calendars>

<scheduledswitchs>
<scheduledswitch name="pompe" switch="pompeswitch" calendar="pompecal"/>
<scheduledswitch name="robot" switch="robotswitch" calendar="robotcal"/>
<scheduledswitch name="lumiere" switch="lumiereswitch" calendar="lumierecal"/>
</scheduledswitchs>

</config>